version: '3.7'
services:
    dw:
        # docker run -p 5433:5432 --name poc-dw -e POSTGRES_USER=poc -e POSTGRES_PASSWORD=poc -e POSTGRES_DB=poc -d postgres:13
        # psql -h poc-dw -U poc -d poc
        container_name: poc-dw
        hostname: poc-dw
        # image: postgres:13
        image: poc-dw-image
        build:
            context: .
            dockerfile: Dockerfile.dw
        environment:
            - POSTGRES_USER=poc
            - POSTGRES_PASSWORD=poc
            - POSTGRES_DB=poc
        restart: always
        ports:
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"

    etl:
        container_name: poc-etl
        # Spark fails if hostname has underscore
        hostname: poc-etl
        depends_on:
            - postgres
        image: poc-pyspark-image
        build:
            context: .
            dockerfile: Dockerfile.etl
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        entrypoint: /bin/bash
        # command: [ "ingest", "report"]
        environment:
            - ENV_DESC=POC
        logging:
            options:
                max-size: 10m
                max-file: "3"
